apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: maalekort-altinn2-adapter
  namespace: styringsinformasjon
  labels:
    team: styringsinformasjon
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /isReady
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /prometheus
  ingresses:
    - "https://maalekort-altinn2-adapter.intern.nav.no"
  kafka:
    pool: nav-prod
  env:
  gcp:
    sqlInstances:
      - autoBackupHour: 1
        cascadingDelete: true
        collation: nb_NO.UTF8
        databases:
          - envVarPrefix: GCP_DB
            name: maalekort
        diskAutoresize: true
        diskSize: 5
        diskType: SSD
        maintenance:
          day: 1
          hour: 4
        name: maalekort-instance-dev
        tier: db-f1-micro
        type: POSTGRES_15
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
