apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-altinn-maalekort-mottatt-v2
  namespace: styringsinformasjon
  labels:
    team: styringsinformasjon
  annotations:
    dcat.data.nav.no/title: "Målekort fra NAV enhet"
    dcat.data.nav.no/description: "Informasjonen er maskininnsending via altinn.no og sendt inn til NAV."
    dcat.data.nav.no/catalog: "internal"
spec:
  pool: {{kafka-pool}}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 168
  acl:
    - team: styringsinformasjon
      application: maalekort-altinn2-adapter
      access: read
    - team: alf
      application: altinnkanal-2
      access: readwrite
    - team: alf
      application: altinn-metrics
      access: read
